# Neural Network

This is the core of our project. For running this, you need to have created three accordingly formatted splits of the data by running these files from the repository:
* preprocessing.sh
* splitting_data.py

You don't need to run the following files because this Notebook accesses them directly:
* data_loading.py
* tokenizer.py
* embeddings.py

## Imports

In [1]:
import datasets
import transformers
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt
from tokenizer import tokenize_and_encode, encode_pos
from embeddings import embedding_model

## Data
Please insert the names of the three splits below:

In [2]:
training_file = "sample_train.tsv"
validation_file = "sample_val.tsv"
test_file = "sample_test.tsv"

## Loading the data

In [3]:
data_files = {
            "train": training_file,
            "test": test_file,
            "validation": validation_file
        }

data_sets = datasets.load_dataset("data_loading.py", data_files=data_files)

Using custom data configuration default-eb9e404412238167
Reusing dataset sample (C:\Users\Luisa\.cache\huggingface\datasets\sample\default-eb9e404412238167\0.0.0\b17a92fd5558fd4c73932ea4beb2edc3fd0b9014fe60a7232b02b67dc71bf1b0)


## Tokenizing the data

In [4]:
# tokens
tokenized_train = tokenize_and_encode("train", data_sets)
tokenized_test = tokenize_and_encode("test", data_sets)
tokenized_validation = tokenize_and_encode("validation", data_sets)
# lists of dictionaries with keys: "input_ids", "token_type_ids", "attention_mask"

# pos-tags
pos_encoded_train = encode_pos("train", data_sets)
pos_encoded_test = encode_pos("test", data_sets)
pos_encoded_validation = encode_pos("validation", data_sets)

print(tokenized_train[0]) # first sentence, tokenized
print(tokenized_train[0]["input_ids"].shape)
print(pos_encoded_train[0]) # first sentence, pos, tokenized
print(pos_encoded_train[0]["input_ids"].shape)

{'input_ids': tensor([[  101, 20802, 15624,  6718,  3128,  5571,   117, 19869, 10753,   117,
          1347,  2518,   117,  1118, 13509, 18745,  8745,  4553, 26197,  1105,
         20802, 13284,  1179, 26197,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 0, 0, 0, 0, 0

## Embeddings
!Attention: This takes very long and I am not sure whether it is even needed or better done inside the network! (so maybe don't run it)

In [ ]:
embeddings_train = list()
for sentence in tokenized_train:
    embeddings_train.append(embedding_model(sentence["input_ids"]))
    
embeddings_test = list()
for sentence in tokenized_train:
    embeddings_test.append(embedding_model(sentence["input_ids"]))
    
embeddings_validation = list()
for sentence in tokenized_validation:
    embeddings_validation.append(embedding_model(sentence["input_ids"]))
    
embeddings_train[0] # embeddings for first sentence

In [ ]:
print(embeddings_train[0][0].shape)
embeddings_train[0][1].shape

## Defining Hyperparameters

In [25]:
sequence_length = 73
# others will be extracted from the code below in the end

## Network architecture
For the architecture of the network, we decided to go for an LSTM because it work well for sequence processing while at the same time handling vanishing and exploding gradients better than a regular RNN.<br>

I found the following architecture online. <br>
My problem is that I don't know where to do the embeddings.
Many implementations I have seen have an embedding layer inside the network and they use nn.Embedding. But this doesn't exactly go with my embeddings implementation (see Embeddings above). How am I supposed to incorporate the embeddings?<br>

Also, I have no idea how to decide on any of the hyperparameters. (I am very unexperienced as you can probably already tell)<br>

And: How do I include the tracking tool wandb?<br>

Note: The below implementation does not work. I haven't had time to debug yet. Any suggestions are very welcome.

In [28]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_size = 768
sequence_length = 73
num_layers = 2
hidden_size = 256
num_classes = 41
learning_rate = 0.001
batch_size = 64
num_epochs = 2

class LSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(LSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers)
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(1), self.hidden_size).to(device)
        c0 = torch.zeros(self.num_layers, x.size(1), self.hidden_size).to(device)
        
        out, _ = self.lstm(x, (h0,c0))
        out = self.fc(out[:,-1,:])
        return out

## Model instantiation

In [30]:
model = LSTM(input_size, hidden_size, num_layers, num_classes).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

## Training loop

In [40]:
num_epochs = 1
for epoch in range(num_epochs):
    for batch_idx, sentence in enumerate(tokenized_train):
        target = pos_encoded_train[batch_idx]["input_ids"]
        
        print(batch_idx, sentence["input_ids"])
        print(sentence["input_ids"].shape)
        print(target)
        print(target.shape)
        
        # do embeddings
        embedded = embedding_model(sentence["input_ids"])
        # shape = [1,73,768]
        input = embedded["last_hidden_state"]
        print(input)
        print(input.shape)
        print(input.size(1))
        
        embedded_pos = embedding_model(target)
        print(embedded_pos["last_hidden_state"])
        print(embedded_pos["last_hidden_state"].shape)
        Y = embedded_pos["last_hidden_state"]
        
        # feed into model
        scores = model(input)
        print(scores[0])
        print(scores.shape, scores[0].shape)
        loss = criterion(scores, Y)
        print(loss)
        break

0 tensor([[  101, 20802, 15624,  6718,  3128,  5571,   117, 19869, 10753,   117,
          1347,  2518,   117,  1118, 13509, 18745,  8745,  4553, 26197,  1105,
         20802, 13284,  1179, 26197,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]])
torch.Size([1, 73])
tensor([[101,  18,  18,  18,   1,  18,   1,  18,  17,   1,  12,  20,  18,  18,
           6,  18,  18, 102,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0

RuntimeError: 1D target tensor expected, multi-target not supported

In [ ]:
#nothing

In [24]:
n_epochs = 3

for epoch in range(n_epochs):
    
    epoch_loss = 0.0
    
    # get all sentences and corresponding tags in the training data
    for n, sentence in enumerate(tokenized_train):
        
        # zero the gradients
        model.zero_grad()

        # zero the hidden state of the LSTM, this detaches it from its history
        model.hidden = model.init_hidden()

        # prepare the inputs for processing by out network
        x = sentence["input_ids"]
        print(x)
        print(x.shape)
        y_gold = pos_encoded_train[n]["input_ids"]
        print(y_gold)
        print(y_gold.shape)

        # forward pass to get tag scores
        tag_scores = model(x) # doesn't work for whatever reason

        # compute the loss, and gradients 
        loss = loss_function(tag_scores, y_gold)
        epoch_loss += loss.item()
        loss.backward()
        
        # update the model parameters with optimizer.step()
        optimizer.step()

tensor([[  101, 20802, 15624,  6718,  3128,  5571,   117, 19869, 10753,   117,
          1347,  2518,   117,  1118, 13509, 18745,  8745,  4553, 26197,  1105,
         20802, 13284,  1179, 26197,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]])
torch.Size([1, 73])
tensor([[101,  18,  18,  18,   1,  18,   1,  18,  17,   1,  12,  20,  18,  18,
           6,  18,  18, 102,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,


IndexError: index out of range in self